### ISSUE TITLE
Замечания по 1 лабе

### ISSUE THREAD

**Issue by nightnoryu** [lich906/operating-systems#1]
## Алгоритм

1. Вектор потоков и так слишком жирно, а тут еще происходит ненужное копирование

https://github.com/lich906/operating-systems/blob/3c4321e8eb8c97fa4539d30e4a8e462ef8c0a1b0/convert/MealyMachineTable.cpp#L16

Лучше использовать `emplace_back` и передавать rvalue.

2. Вместо этого лучше просто сразу зарезервировать в векторе 1 позицию и дальше добавлять через `push_back`

https://github.com/lich906/operating-systems/blob/3c4321e8eb8c97fa4539d30e4a8e462ef8c0a1b0/convert/MealyMachineTable.cpp#L65-L67

3. С обычной `map` тут выходит сложность n^2 log n

https://github.com/lich906/operating-systems/blob/3c4321e8eb8c97fa4539d30e4a8e462ef8c0a1b0/convert/MealyMachineTable.h#L34

Т.к. тут порядок не важен, лучше использовать `unordered_map`

## Код

1. Почему бы вместо поясняющего комментария не использовать структуру

https://github.com/lich906/operating-systems/blob/3c4321e8eb8c97fa4539d30e4a8e462ef8c0a1b0/convert/MealyMachineTable.h#L10-L14

2. Аналогично и тут

https://github.com/lich906/operating-systems/blob/3c4321e8eb8c97fa4539d30e4a8e462ef8c0a1b0/convert/MealyMachineTable.h#L69-L79

Мапу в мапе становится сложно воспринимать

**Comment by lich906** [comment]
## Алгоритм
1. Переписал так
https://github.com/lich906/operating-systems/blob/eda288c66ebca8cf7e2caad1759e056f3205ff35/convert/MealyMachineTable.cpp#L16
2. Зарезервировал на этапе конструирования
https://github.com/lich906/operating-systems/blob/eda288c66ebca8cf7e2caad1759e056f3205ff35/convert/MealyMachineTable.cpp#L65
3. Переделал на `unordered_map`.
https://github.com/lich906/operating-systems/blob/eda288c66ebca8cf7e2caad1759e056f3205ff35/convert/MealyMachineTable.h#L19
Пришлось добавить кустОмный хешер
https://github.com/lich906/operating-systems/blob/eda288c66ebca8cf7e2caad1759e056f3205ff35/convert/MealyMachineTable.h#L74-L82

## Код
Добавил структур.
